// ============================================================================
// Schema v2.0 - Primary Types
// (Character storage is v3.0 per-character files — see CharacterFile and
//  docs/schema_characters_v3.md; dialogue/voices lines are separate)
// ============================================================================

export type TtsProvider = 'vibevoice_local';
export type Gender = 'Male' | 'Female' | 'Unknown';

// === Characters (Story Characters) ===

export interface Character {
  guid: string | null;  // v3 identity (8-char Crockford base32; see CHARACTER_GUID_PATTERN). Invariant: every persisted v3 character file has a non-null guid; in-memory derived records (derive-from-chapters fallback) may carry null.
  id: string;  // Documented mirror of guid in v3 (id = guid) so existing read sites keep working
  name: string;  // Display name
  gender: Gender;
  aliases: string[];
  descriptors?: string[];
  race?: string;  // Character race/species (optional)
  color: string | null;
  notes: string;
  firstAppearance: string | null;  // Chapter ID
  stats: {
    totalLines: number;
    chapterCount: number;
  };
  // Legacy/optional voice-related properties (for backward compatibility)
  voice?: string | null;
  provider?: TtsProvider | null;
  voiceId?: string | null;
  voiceMeta?: CharacterVoiceMeta | null;
  manifestStats?: CharacterManifestStats | null;
  count?: number;  // Legacy: use stats.totalLines instead
  chapterCount?: number;  // Legacy: use stats.chapterCount instead
}

// v3 character GUID: 8 chars, uppercase Crockford base32 (0-9 + A-Z minus I, L, O, U).
// Normative spec: docs/schema_characters_v3.md §GUID spec.
export const CHARACTER_GUID_PATTERN = /^[0-9A-HJKM-NP-QRSTV-Z]{8}$/;

/**
 * Normalize a free-form gender value to the canonical `Gender` union.
 * Pure (no service imports): kept in this dependency-free module so
 * fs-independent modules (e.g. characterFileMapping) can use it without
 * pulling in the fs import chain.
 */
export function normalizeCharacterGender(value: unknown): Gender {
  const normalized = String(value || '').trim().toLowerCase();
  if (normalized === 'male' || normalized === 'm') return 'Male';
  if (normalized === 'female' || normalized === 'f') return 'Female';
  return 'Unknown';
}

/**
 * v3.0 per-character file record: characters/<Title>.json (one file per alias cluster).
 * Normative field table: docs/schema_characters_v3.md §File format.
 */
export interface CharacterFile {
  formatVersion: string;  // Must be "3.0" (character version line, independent of the dialogue line)
  guid: string;  // The identity; immutable for the cluster's life (see CHARACTER_GUID_PATTERN)
  title: string;  // Display name; filename derives from it (changing it = file rename)
  gender: Gender;
  aliases: string[];  // Surface forms; the title is the display name, full stop
  descriptors: string[];
  race?: string | null;
  color: string | null;
  notes: string;
  firstAppearance: string | null;  // Derived; regenerated by the stats pass
  stats: {
    totalLines: number;
    chapterCount: number;
  };
  // Optional voice-related properties (as v2)
  voice?: string | null;
  provider?: TtsProvider | null;
  voiceId?: string | null;
  voiceMeta?: CharacterVoiceMeta | null;
  manifestStats?: CharacterManifestStats | null;
  roleLabels?: string[];  // Must round-trip: read by dialogue_ai_context.py:288
  updatedAt: string;  // ISO; set on every write; used for duplicate-GUID reconciliation (newest wins)
}

/** @deprecated Legacy v2 characters.json shape — read-only after migration; v3 writers target the characters/ folder (CharacterFile). */
export interface CharactersJson {
  formatVersion: string;
  characters: Character[];
}

// === Voices (TTS Voices / Speakers) ===

export interface Voice {
  id: string;  // Unique voice ID (e.g., "vibevoice_local-my_sample.wav")
  displayName: string;  // UI display name (e.g., "Black Knight Voice", "Narrator")
  provider: TtsProvider;
  providerVoiceId: string;  // Local sample/voice identifier for VibeVoice
  previewUrl: string | null;
  notes: string;  // User notes about the voice/speaker
  metadata: {
    // Legacy metadata fields retained for compatibility with older voices.json files.
    gender?: 'M' | 'F' | 'U';  // Male, Female, Unknown
    ageRange?: string;  // "young-adult", "adult", etc.
    accent?: string;  // "neutral", "en-US", etc.
    tags?: string[];  // ["clear", "confident", ...]
    imageUrl?: string | null;  // Optional image for the voice
    // Audio generation stats
    totalClips?: number;  // Total clips generated with this voice
    usedByCharacters?: string[];  // Character IDs using this voice
    discoveredFrom?: 'manifest' | 'manual' | 'sample';  // How was this voice added
  };
}

export interface VoiceAssignment {
  characterId: string;  // Reference to character.id
  voiceId: string;  // Reference to voice.id
  priority: number;  // 1 = primary, higher = fallback
  contextOverrides: any[];  // Future: emotion-specific overrides
}

export interface VoicesJson {
  formatVersion: string;
  voices: Voice[];
  assignments: VoiceAssignment[];
}

// === Dialogue Lines ===

export interface LineCandidate {
  characterId: string;  // Reference to character.id
  confidence: number;  // 0.0 to 1.0
}

export interface LineMetadata {
  emotion: string | null;  // "neutral", "angry", "sad", etc.
  intensity: number;  // 0.0 to 1.0
  pacing: string | null;  // "slow", "normal", "fast"
  prefix: string | null;  // Custom prefix like "[shouting]"
  customTags: Record<string, any>;  // Arbitrary key-value pairs
}

export type AttributionResolutionStatus = 'auto' | 'unknown' | 'user_confirmed';

export interface LineAttributionCandidate {
  characterId: string | null;
  name: string;
  confidence: number;
  reasons?: string[];
}

export interface LineAttributionDecisionTrace {
  selectedCandidate?: string | null;
  selectedReasons?: string[];
  overrideReason?: string | null;
  signals?: Record<string, any>;
}

export interface LineAttribution {
  confidence: number;
  topCandidateConfidence: number;
  marginToSecond: number;
  misattributionRisk: number;
  resolutionStatus: AttributionResolutionStatus;
  thresholdUsed: number;
  sourceAlias: string | null;
  sourceCandidates?: string[];
  sourceDescriptors?: string[];
  contextGender?: string | null;
  contextGenderCue?: string | null;
  genderConflict?: boolean;
  parserBackend?: string | null;
  decisionTrace?: LineAttributionDecisionTrace | null;
  candidates: LineAttributionCandidate[];
}

export interface ParserLineAttribution {
  parserBackend?: string | null;
  contextGender?: string | null;
  contextGenderCue?: string | null;
  genderConflict?: boolean;
  candidates?: LineAttributionCandidate[];
  decisionTrace?: LineAttributionDecisionTrace | null;
}

export interface DialogueLine {
  id: number;
  characterId: string | null;  // Reference to character.id (null defaults to narrator)
  isNonSpeaker?: boolean;  // Explicitly dismissed as not spoken dialogue
  text: string;
  span: { start: number; end: number } | null;
  metadata: LineMetadata;
  candidates: LineCandidate[];
  isConflict: boolean;
  isReturning?: boolean;
  attribution?: LineAttribution;
}

export interface DialogueJson {
  formatVersion: string;
  chapterId: string;
  reviewed?: boolean;
  reviewedAt?: string | null;
  reviewedLineCount?: number;
  lines: DialogueLine[];
  stats: {
    totalLines: number;
    conflicts: number;
    characterBreakdown: Record<string, number>;  // characterId → count
  };
}

// === UI Types ===

export type ParagraphRun = {
  text: string;
  characterId: string | null;  // Changed from "speaker" to "characterId"
  lineId?: number;
};

// ============================================================================
// Legacy v1.0 Types (for backward compatibility during migration)
// ============================================================================

/** @deprecated Use DialogueLine instead */
export interface LineItem {
  id: number;
  text: string;
  span: { start: number; end: number } | null;
  chosenSpeaker: string | null;  // v1: character name (not ID)
  isNonSpeaker?: boolean;
  candidates: { name: string; confidence: number }[];  // v1: uses name
  isConflict: boolean;
  isReturning?: boolean;
  attribution?: {
    confidence?: number;
    topCandidateConfidence?: number;
    marginToSecond?: number;
    misattributionRisk?: number;
    resolutionStatus?: AttributionResolutionStatus;
    thresholdUsed?: number;
    sourceAlias?: string | null;
    sourceCandidates?: string[];
    sourceDescriptors?: string[];
    contextGender?: string | null;
    contextGenderCue?: string | null;
    genderConflict?: boolean;
    parserBackend?: string | null;
    decisionTrace?: LineAttributionDecisionTrace | null;
    candidates?: { name: string; characterId?: string | null; confidence: number; reasons?: string[] }[];
  };
}

/** @deprecated Use DialogueJson instead */
export interface ScriptJson {
  chapter: string;
  sourceFile: string;
  lines: LineItem[];
  stats: { numConflicts: number; numLines: number };
}

/** @deprecated Use Character instead */
export interface CharacterConfig {
  id?: string;
  name: string;
  gender?: Gender;
  aliases?: string[];
  descriptors?: string[];
  color: string | null;
  voice: string | null;
  notes?: string;
  stats?: {
    totalLines: number;
    chapterCount: number;
  };
  count?: number;
  provider?: TtsProvider | null;
  voiceId?: string | null;
  voiceMeta?: CharacterVoiceMeta | null;
  manifestStats?: CharacterManifestStats | null;
  firstAppearance?: string | null;
  chapterCount?: number;
}

export interface CharacterVoiceMeta {
  name?: string;
  previewUrl?: string | null;
  fetchedAt?: string;
  provider?: TtsProvider;
}

export interface CharacterManifestStats {
  clipCount: number;
  totalLines: number;
  voiceIds: Record<string, number>;
  coverageRatio?: number;
  primaryVoiceId?: string | null;
  lastUpdated?: string;
}

// ============================================================================
// Parser Types (from Python service)
// ============================================================================

export type Script = Line[];

export interface Line {
  id: number;
  segments: Segment[];
  speaker: string;  // Character name from parser
  line_type: 'narration' | 'dialogue';
  is_suggestion: boolean;
  suggestions: any[];
  span_start?: number;
  span_end?: number;
  attribution?: ParserLineAttribution;
}

export type Segment = TextSegment | PauseSegment;

export interface TextSegment {
  type: 'text';
  value: string;
}

export interface PauseSegment {
  type: 'pause';
  duration: 'short' | 'medium' | 'long';
}

// ============================================================================
// Settings & Configuration
// ============================================================================

export interface AudiobookSettings {
  narratorSameAsProtagonist: boolean;
  narratorVoice?: VoiceAssignment;
  defaultAccent: string;
  speakingRate: number; // 1.0 default
  allowMultipleNarrators?: boolean;
  narrators?: string[];
  protagonist?: string | null;
  mainCharacters?: string[];
  sideCharacters?: string[];
}

export interface ParserHints {
  parserBackend?: 'legacy' | 'modernbooknlp';
  protagonistName?: string;
  protagonistNames?: string[];
  povMode?: 'first_person' | 'third_person';
  learnVerbs?: boolean;
  heuristics?: {
    protagonistFirstPersonTag?: boolean;
    narratorIdentity?: boolean;
    coreference?: boolean;
    explicitTags?: boolean;
    tagContinuation?: boolean;
    contiguousDialogue?: boolean;
    carryAcrossShortNarration?: boolean;
    suggestAlternatives?: boolean;
    firstPersonOverride?: boolean;
    narratorFallback?: boolean;
    vocativeGuard?: boolean;
  };
  manualBlockList?: string[];  // Character names to block during parsing
  attribution?: {
    unknownThreshold?: number;
  };
}

// ============================================================================
// Voice Models (for UI)
// ============================================================================

export interface VoiceModel {
  voiceId: string;
  name: string;
  provider: TtsProvider;
}

